# Generated by Django 3.2 on 2021-04-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usageRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usageField', models.CharField(max_length=20)),
                ('usageRate', models.IntegerField()),
            ],
        ),
    ]
