# Generated by Django 3.2 on 2021-04-26 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kisiBasiCekilenSu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waterpercapita',
            old_name='year',
            new_name='_year',
        ),
    ]
