# Generated by Django 3.2 on 2021-04-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='damVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('area', models.CharField(max_length=15)),
            ],
        ),
    ]
