# Generated by Django 3.2 on 2021-04-26 12:32

import django.core.validators
from django.db import migrations, models
import istanbulnufus.models


class Migration(migrations.Migration):

    dependencies = [
        ('istanbulnufus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='istanbulnufus',
            old_name='nufus',
            new_name='population',
        ),
        migrations.AlterField(
            model_name='istanbulnufus',
            name='year',
            field=models.IntegerField(),
        ),
    ]
