# Generated by Django 3.2 on 2021-04-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istanbulnufus', '0002_istanbulnufus_givenwater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='istanbulnufus',
            name='givenWater',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='istanbulnufus',
            name='population',
            field=models.IntegerField(),
        ),
    ]
