# Generated by Django 3.2 on 2021-04-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istanbulnufus', '0002_auto_20210426_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='istanbulnufus',
            name='year',
            field=models.IntegerField(unique=True),
        ),
    ]
